---
# Defaults Ansible Logic

# It was important to use ansible connection CLI for SSH with NXOS as otherwise nothing worked. I Defined it here.
ansible_connection: network_cli
# Global System Settings

ntp_servers:
  - 1.1.1.1
  - 2.2.2.2

# Project Directory

directory: /home/george/Desktop/ansible-projects
